// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console2} from "forge-std/Script.sol";

import {MockWETH} from "../test/mocks/MockWETH.sol";
import {MockUniswapV2Factory} from "../test/mocks/MockUniswapV2.sol";
import {MockUniswapV2Router} from "../test/mocks/MockUniswapV2Router.sol";

import {LocalAnvilConfig} from "./config/LocalAnvilConfig.sol";

/// @title DeployLocalDex
/// @notice Deploy mock Uniswap V2 stack on Anvil (no external DEX required).
contract DeployLocalDex is Script {
    string internal constant DEX_ENV_PATH = "deployments/anvil-dex.env";

    function run() external {
        if (block.chainid != LocalAnvilConfig.CHAIN_ID) {
            revert("DeployLocalDex: run on Anvil chain 31337 only");
        }

        console2.log("[DeployLocalDex] chainId", block.chainid);
        console2.log("[DeployLocalDex] broadcaster", msg.sender);

        vm.startBroadcast();

        MockWETH weth = new MockWETH();
        MockUniswapV2Factory factory = new MockUniswapV2Factory();
        MockUniswapV2Router router = new MockUniswapV2Router(address(factory), address(weth));

        vm.stopBroadcast();

        string memory snippet = string.concat(
            "# Generated by DeployLocalDex.s.sol\n",
            "UNISWAP_V2_ROUTER=", vm.toString(address(router)), "\n",
            "MOCK_DEX_FACTORY=", vm.toString(address(factory)), "\n",
            "MOCK_WETH=", vm.toString(address(weth)), "\n"
        );
        vm.writeFile(DEX_ENV_PATH, snippet);

        console2.log("mockWeth", address(weth));
        console2.log("mockFactory", address(factory));
        console2.log("mockRouter", address(router));
        console2.log("Saved", DEX_ENV_PATH);
    }
}
